language: java
branches:
  only:
  - master
  - /travis/
  - "/.*-[0-9]+\\..*/"
before_install:
  - wget https://www.dropbox.com/s/h70d7erl2mkufbk/jdk-8u241-linux-x64.tar.gz?dl=1
  - tar -xvzf jdk-8u241-linux-x64.tar.gz?dl=1
  - mv jdk1.8.0_241 jdk
  - export JAVA_HOME=`pwd`/jdk
  - export PATH=${JAVA_HOME}/bin:${PATH}
  - echo $JAVA_HOME
  - java -version
  - wget http://mirrors.advancedhosters.com/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar -xvzf apache-maven-3.6.3-bin.tar.gz
  - mv apache-maven-3.6.3 maven
  - export M2_HOME=`pwd`/maven
  - export PATH=${M2_HOME}/bin:${PATH}
  - mvn -version
  - java -version
install: true
script: ".travis/build.sh"
env:
  global:
    secure: rn+NMW27eoVIPRMr56Ds8Bkaj53n5s6dZm+wbpjltmDusAI5Fh8rFZCa5KBE4EExOpOotBPeuYm4USCVYTju5yum3ybG9XXxGbUj/foQLodArTPggDWdL7iU+lge0nQFeuSqeyeqgeiSoE2Q4vB6HBCSRQnx3dTWrH0WzjuAHLxJRqrdGVcjhqQFe49MKsVUcF50DQl+Rcg6TpZ4YBBElxY/rkG5JcEXVTlCHK0gLKjNOojU/1Xq3uoyxJLAs2r2WlutsqboLnWqP0iYyOXa+TptR0CvTestO4M6TWNDokTy4HjviUvvIldCYBtwaUNlv7MQjUFs2Oeu+ohuNvnR2OFU+Gy67/f2kk8c3s130WD4RTTVIdBp7mASdIV7K6vi8chPLEbZKaVTPf3InsaUpHSVXf1abNUSU/dXZAxucl9JJ/9zf2ALToqgR4EcAsYCfsTaK3RP4Xk2Y3XwGNXXTi4dHMenS5zleetwCzszrsCNQ53ltwZsoqdS1EVg2ZSr0TKyKS51YJg3+cOtH2/V6u1/NuSvVbuAXpQeLlPaus13IH7TR2rtZp82UKofNLmlbc6isgy0SxV6xe/WT9S/G+IOADxhp8/dmhJ6g25c1d/YtxLtkjk5sTiJP+4rVKO5dkV/vltvc8V+Zw9KR2GwuMHDG8fBEuK9D209fQQJwtc=
