version: '3.1'
services:
  api:
    image: "${VCELL_REPO_NAMESPACE}/vcell-api:${VCELL_TAG}"
    environment:
      - softwareVersion=${VCELL_VERSION}
      - serverid=${VCELL_SITE}
      
      - dburl=${VCELL_DB_URL}
      - dbdriver=${VCELL_DB_DRIVER}
      - dbuser=${VCELL_DB_USER}

      - jmsuser=clientUser
      - jmshost_internal=activemq
      - jmsport_internal=61616
      - jmsrestport_internal=8161
      - mongodb_host_internal=mongodb
      - mongodb_port_internal=27017
      - mongodb_database=test

      - smtp_hostname=${VCELL_SMTP_HOSTNAME}
      - smtp_port=${VCELL_SMTP_PORT}
      - smtp_emailaddress=${VCELL_SMTP_EMAILADDRESS}

    ports:
      - "${VCELL_API_PORT_EXTERNAL}:8080"
      - "8000" # java remote debugging
    secrets:
      - keystorefile
      - keystorepswd
      - dbpswd
      - jmspswd
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 2000M
        reservations:
          memory: 1000M
  master:
    image: "${VCELL_REPO_NAMESPACE}/vcell-master:${VCELL_TAG}"
    environment:
      - softwareVersion=${VCELL_VERSION}
      - serverid=${VCELL_SITE}
      - singularity_imagefile=${VCELL_SINGULARITY_IMAGE_EXTERNAL}
      - docker_name=${VCELL_BATCH_DOCKER_IMAGE}

      - dburl=${VCELL_DB_URL}
      - dbdriver=${VCELL_DB_DRIVER}
      - dbuser=${VCELL_DB_USER}

      - jmshost_external=${VCELL_JMS_HOST_EXTERNAL}
      - jmsrestport_external=${VCELL_JMS_RESTPORT_EXTERNAL}
      - jmsport_external=${VCELL_JMS_PORT_EXTERNAL}

      - mongodb_host_external=${VCELL_MONGO_HOST_EXTERNAL}
      - mongodb_port_external=${VCELL_MONGO_PORT_EXTERNAL}
      - simdatadir_external=${VCELL_SIMDATADIR_EXTERNAL}
      - simdatadir_parallel_external=${VCELL_SIMDATADIR_PARALLEL_EXTERNAL}
      - export_baseurl=${VCELL_EXPORT_BASEURL}

      - batchhost=${VCELL_BATCH_HOST}
      - batchuser=${VCELL_BATCH_USER}
      - htclogdir_external=${VCELL_HTCLOGS_EXTERNAL}
      - nativesolverdir_external=${VCELL_NATIVESOLVERDIR_EXTERNAL}
      - htcnodelist=${VCELL_HTC_NODELIST}
      - batchsystem=SLURM
      - slurm_cmd_sbatch=${VCELL_SLURM_CMD_SBATCH:-slurm}
      - slurm_cmd_sacct=${VCELL_SLURM_CMD_SACCT:-sacct}
      - slurm_cmd_squeue=${VCELL_SLURM_CMD_SQUEUE:-squeue}
      - slurm_cmd_scancel=${VCELL_SLURM_CMD_SCANCEL:-scancel}
      - slurm_partition=${VCELL_SLURM_PARTITION:-vcell}
      - slurm_tmpdir=${VCELL_SLURM_TMPDIR}
      - maxJobsPerScan=${VCELL_MAX_JOBS_PER_SCAN:-100}
      - maxJobsPerSite=${VCELL_MAX_JOBS_PER_SITE:-100}
      - maxOdeJobsPerUser=${VCELL_MAX_ODE_JOBS_PER_USER:-50}
      - maxPdeJobsPerUser=${VCELL_MAX_PDE_JOBS_PER_USER:-50}
      - simdataCacheSize=${VCELL_SIMDATA_CACHE_SIZE:-10000000}

      - jmsuser=clientUser
      - jmshost_internal=activemq
      - jmsport_internal=61616
      - jmsrestport_internal=8161
      - mongodb_host_internal=mongodb
      - mongodb_port_internal=27017
      - mongodb_database=test
    ports:
      - "8000" # java remote debugging
    volumes:
      - "${VCELL_SIMDATADIR_HOST}:/simdata"
      - "${VCELL_EXPORTDIR_HOST}:/exportdir"
      - "${VCELL_HTCLOGS_HOST}:/htclogs"
    secrets:
      - dbpswd
      - jmspswd
      - batchuserkeyfile
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 3000M
        reservations:
          memory: 1000M
      placement:
        constraints:
          - node.labels.zone == INTERNAL
  db:
    image: "${VCELL_REPO_NAMESPACE}/vcell-db:${VCELL_TAG}"
    environment:
      - softwareVersion=${VCELL_VERSION}
      - serverid=${VCELL_SITE}

      - dburl=${VCELL_DB_URL}
      - dbdriver=${VCELL_DB_DRIVER}
      - dbuser=${VCELL_DB_USER}

      - jmsuser=clientUser
      - jmshost_internal=activemq
      - jmsport_internal=61616
      - jmsrestport_internal=8161

      - mongodb_host_internal=mongodb
      - mongodb_port_internal=27017
      - mongodb_database=test
    secrets:
      - dbpswd
      - jmspswd
    networks:
      - vcellnet
    depends_on:
      - activemq
      - mongodb
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - "${VCELL_JMS_PORT_EXTERNAL}:61616"
      - "${VCELL_JMS_RESTPORT_EXTERNAL}:8161"
    environment:
      - ACTIVEMQ_STATIC_QUEUES=simReq;dataReq;dbReq;simJob;workerEvent
      - ACTIVEMQ_STATIC_TOPICS=serviceControl;daemonControl;clientStatus
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_USERS_clientUser=dummy
      - ACTIVEMQ_GROUPS_reads=clientUser
      - ACTIVEMQ_GROUPS_writes=clientUser
      - ACTIVEMQ_CONFIG_AUTHENABLED=true
    networks:
      - vcellnet
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2000M
        reservations:
          memory: 1000M
      placement:
        constraints:
          - node.labels.zone == INTERNAL
  mongodb:
    image: "${VCELL_REPO_NAMESPACE}/vcell-mongo:${VCELL_TAG}"
    ports:
      - "${VCELL_MONGO_PORT_EXTERNAL}:27017"
    networks:
      - vcellnet
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1500M
        reservations:
          memory: 1000M

networks:
  vcellnet:
secrets:
  dbpswd:
    file: ${VCELL_SECRETS_DIR}/dbpswd.txt
  jmspswd:
    file: ${VCELL_SECRETS_DIR}/jmspswd.txt
  keystorepswd:
    file: ${VCELL_SECRETS_DIR}/vcellapi-beta-keystorepswd.txt
  keystorefile:
    file: ${VCELL_SECRETS_DIR}/vcellapi-beta.jks
  batchuserkeyfile:
    file: ${VCELL_SECRETS_DIR}/schaff_rsa
