name: Publish simulator to GHCR and BioSimulators
on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout out
      - uses: actions/checkout@v2
      # Build and push Docker image

      -name: Build and Push Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          image_name: vcell/biosimulators_vcell
          image_tag: ${{ github.event.release.tag_name }} )
          push_git_tag: false
          registry: ghcr.io
          context: .
          dockerfile: Dockerfile
          

      - name: Tag the docker image with the latest tag
        if: ${{steps.tagLatest.outputs.tagLatest=='True'}}
        run: |
          docker tag  ghcr.io/virtualcell/biosimulators_vcell::${{ github.event.release.tag_name }}  ghcr.io/virtualcell/biosimulators_vcell:latest 
          docker push --all-tags ghcr.io/virtualcell/biosimulators_vcell
      # Submit to BioSimulators registry
      - name: Submit to BioSimulators registry
        run: |
          REVISION=$(git rev-parse HEAD)
          curl \
            -X POST \
            -u $${{ secrets.DOCKER_REGISTRY_USERNAME }}:${{ secrets.DOCKER_REGISTRY_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/biosimulators/Biosimulators/issues \
            -d "{\"labels\": [\"Validate/submit simulator\"], \"title\": \"Submit VCell ${{ github.event.release.tag_name}}\", \"body\": \"---\nid: vcell\nversion: ${{ github.event.release.tag_name }}\nspecificationsUrl: https://raw.githubusercontent.com/${{ github.repository }}/${REVISION}/biosimulators.json\nspecificationsPatch:\n  version: ${{ github.event.release.tag_name }}\n  image:\n    url: ghcr.io/biosimulators/biosimulators_vcell/vcell:${{ github.event.release.tag_name }}\nvalidateImage: true\ncommitSimulator: true\n\n---\"}"
