name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-java@v1
#       with:
#         java-version: '1.8'
#         java-package: jdk
#     - name: Show mvn version
#       run: mvn -version
#     - name: Build with Maven
#       run: mvn clean install dependency:copy-dependencies # mvn -B package --file pom.xml
#     - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file ./docker/build/Dockerfile-sedml-solver --tag crbm/biosimulations_copasi_api:latest
